### ISSUE TITLE
Add Sparsebundle disk image support :D

### ISSUE THREAD

**Issue by adespoton** [zydeco/minivmac4ios#1]
Possible that this is something I should be suggesting to Paul and you'd automatically inherit.  Code for this is in the sheepshaver and BII code for OS X; seems like it should be possible as well on iOS.  Low priority feature request.

**Comment by zydeco** [comment]
I know it's available in the other emulators, but I don't think it's that useful here, the size of the disk image shouldn't be a problem for Mini vMac.

**Comment by adespoton** [comment]
Actually... I've figured out how to do it in minivmac4ios, and now that I can implement it in source, I agree that it's not useful :)  I think you can close this item.  If, for some strange reason, it is desired in the future, I've locally documented what needs to be done.  But even with the slices being at 1MB instead of 8MB like the default, it makes no practical sense to implement this and just add more code to maintain that could possibly break in the future.
