### ISSUE TITLE
No Macintosh hd icon

### ISSUE THREAD

**Issue by 12d3** [zydeco/minivmac4ios#12]
there isn't a hd icon on the Macintosh desk top. it would be really nice if you would add the option to make a disk image or a hard disk image

**Comment by zydeco** [comment]
Mini vMac doesn't emulate an actual hard drive, but it patches the emulated Mac's floppy disk driver to accept disk images of any size (up to 2GB).

You can create disk images by tapping Edit from the Insert Disk menu, and then Create Disk Image.

![screen shot 2016-07-01 at 19 47 46](https://cloud.githubusercontent.com/assets/158216/16529719/c4cf0386-3fc4-11e6-8ba0-bcb83e860e7c.png)

If you rename the disk image to `disk1.dsk`, it will be inserted automatically when starting the emulator.

The disk images with non-standard sizes show in the desktop as a floppy icon with a "v" inside, but if you're using System 7, you can paste a hard disk icon in the Get Info window.
