### ISSUE TITLE
I can't build it using Xcode 7.3.1

### ISSUE THREAD

**Issue by LBPPlayer7** [zydeco/minivmac4ios#14]
I just can't build it. A load of issues comes up and then it says "Build Failed". Did I do something wrong?

**Comment by zydeco** [comment]
You may be missing the submodules (libmfs and libres), if you've checked out out with git you can get them by running: 
`git submodule update --init --recursive`

If you're using a free developer account, you'll also have to change the bundle identifier, there's a tutorial for GBA4iOS here: http://bouk.co/blog/sideload-iphone/

Jesús A. Álvarez

**Comment by zydeco** [comment]
Closing after being inactive for over 60 days
