### ISSUE TITLE
App icon not showing after install from bigboss

### ISSUE THREAD

**Issue by KevinBlue18** [zydeco/minivmac4ios#15]
Hi Jesús,

I'm using an iPhone 5s iOS 9.3.3 jailbreak and after installing Mini vMac from modmyi the app icon is not showing on homescreen. Is there a way to fix this.

**Comment by zydeco** [comment]
The Mini vMac on modmyi is an old version (1.2.2) that's was last updated for iOS 4, it probably doesn't work on iOS 9, I wasn't aware anyone had submitted it there until now.

Does the same happen with the current version (2.2.1) from BigBoss repo?

Does it happen if you install the .deb from GitHub [v2.2.1](https://github.com/zydeco/minivmac4ios/releases/tag/v2.2.1)?

I've heard of this happening for some people with jailbroken devices and iOS 9, for some it works with the deb from GitHub, but I don't have any jailbroken device to try and reproduce it, and it always works if you build it with Xcode.

**Comment by Grintss** [comment]
Hi

I have an iPad mini 2 jailbroken on 8.4 and icon doesn't appear when installing from Cydia or the .deb

**Comment by KevinBlue18** [comment]
Sorry I mean BigBoss

**Comment by KevinBlue18** [comment]
I can't use Xcode I don't have mac

**Comment by KevinBlue18** [comment]
Yup the one from here doesn't show either.

**Comment by zydeco** [comment]
Also, have you run `uicache` after installing the deb from GitHub manually? You must run `uicache` from terminal as `mobile` user, not root.
This forces springboard to read the Applications directory and show any new apps that may have been installed.

**Comment by ARandomRedditor** [comment]
I have run uicache as a mobile user, yet the application will not appear on the SpringBoard.
