### ISSUE TITLE
Missing files errors in Xcode 8

### ISSUE THREAD

**Issue by Attila777** [zydeco/minivmac4ios#16]
I opened the project in Xcode 8, and I updated all the settings it wanted to update. But when I choose the target and click on run it gives me two errors with missing files:
1) /minivmac4ios-master 2/libmfs/mfs.c
2) /minivmac4ios-master/libres/res.c

Where do I find these two files?

Thank you for the great work you did on this project :-)

**Comment by zydeco** [comment]
You need to download the submodules too. From the minivmac4ios directory, run this command:
`git submodule update --init --recursive`
It will create the libmfs and libres directories and download the libraries into them.

**Comment by Attila777** [comment]
Thank you for your reply, but when I run the command in Terminal it gives me the following error:
**"fatal: Not a git repository (or any of the parent directories): .git"**
The way I did it it I right-clicked on the "minivmac4ios-master" folder and chose: **"Services/New Terminal at Folder"**, then pasted the code: **"git submodule update --init --recursive"**

**Comment by Attila777** [comment]
After looking at other forums I typed the "**git init**" comand which created the **.git** folder, now I'm not getting any errors with "git submodule update --init --recursive", but It's still not downloading the two missing files :-( I paste it in but nothing happens.

[img]http://i.imgur.com/VvCYAQH.png[/img]

**Comment by Attila777** [comment]
I re-downloaded your files and tried again. Same error. Here is my screenshot:

http://i.imgur.com/saHRjVx.jpg

**Comment by zydeco** [comment]
When you download a repository from GitHub as a zip file, it doesn't include the submodules, only empty folders. To download everything you must clone the repository using git:

`git clone https://github.com/zydeco/minivmac4ios.git`

Then go into the folder and get the submodules:

`git submodule update --init --recursive`

After this, the libmfs and libres folders should contain some files, and you'll be able to build.

**Comment by Attila777** [comment]
That did it. Thank you :-)
