### ISSUE TITLE
No icon on JB 9.3.3

### ISSUE THREAD

**Issue by KubbaYioka** [zydeco/minivmac4ios#17]
Hello.

I installed mini v mac on a jailbroken 9.3.3 ipad using Cydia, but do not see an icon on the homescreens. Tried reinstalling, uninstalling and fresh install.

Thanks.

**Comment by zydeco** [comment]
What version?

**Comment by KubbaYioka** [comment]
2.2.1

**Comment by zydeco** [comment]
Try the latest 2.2.2, you can download it [here](https://github.com/zydeco/minivmac4ios/releases/tag/v2.2.2) until it's updated in BigBoss.

**Comment by KubbaYioka** [comment]
That seemed to work. Thanks!
