### ISSUE TITLE
Suggestion for Additional Mouse Option.

### ISSUE THREAD

**Issue by KubbaYioka** [zydeco/minivmac4ios#18]
Hello again,

This may seem a little niche, but could it be possible for a bluetooth mouse option that follows a BTC Mouse cursor (or equivalent) in iOS? This would make it easier to play games such as The Colony.

Thanks for your time, and your hard work on this great emulator!

**Comment by zydeco** [comment]
I've implemented this in 9f2e3f8 (using BTC Mouse) but I've only been able to try it on an iPhone 4, which is already quite laggy with emulation, so I'm not sure how useful it is, maybe the speed should be tweaked.
