### ISSUE TITLE
French Keyboard Layout

### ISSUE THREAD

**Issue by jvernet** [zydeco/minivmac4ios#22]
Is there any way to have a french keyboard layout? Which tool do you use to create nfkeyboardlayout files?

**Comment by WeedyWeedSmoker** [comment]
Hi **zydeco** !

I too would be glad to have a french keyboard layout...

Thanks

**Comment by zydeco** [comment]
sorry for the delay, I got a bit caught up trying to read the layout from the emulated mac's memory, but didn't get too far

I've added the french layout manually in 40d9331

Regarding the layouts, they are written in JSON and compiled to a binary format, all the related files are here: https://github.com/zydeco/macemu/tree/ios/BasiliskII/src/iOS/Keyboard%20Layouts

**Comment by WeedyWeedSmoker** [comment]
Thank you so much !

Your implementation is so great... Very much appreciated !
