### ISSUE TITLE
Preset for 16M, 640x480 and 16M, 1024x768 Mac II

### ISSUE THREAD

**Issue by WeedyWeedSmoker** [zydeco/minivmac4ios#25]
Hi !

I would like to ask if it is possible to add presets for 16M, 640x480 and 16M, 1024x768 on the Mac II configuration... It would be perfect for some "memory hungry" applications...

Thank you so much !

_Even 32M and 64M configurations would allow for more advanced stuff, like, playing "Captain Bumper 68k" ! 😄 (which requires 34M of memory)... Thanks !_

**Comment by WeedyWeedSmoker** [comment]
Ok, just read some info on the mini vMac site...

> More memory?

> The Mac Plus (and Mac SE) can support no more than 4MB of memory, since the RAM starts at address 0 and the ROM is at address 0x00400000 (4MB).

> After figuring out how to patch the ROM to support a different size screen, I investigated whether it would be possible to patch the ROM so that it could function elsewhere in the address space. The answer was no. The Macintosh System software, in particular the part that installs bug fixes for traps that otherwise would be implemented ROM, assumes and depends on the exact address of the ROM. It would not be enough to patch the ROM, any System Software version that might be used would have to be patched as well.

> The (incomplete) Macintosh II emulation currently supports up 8MB. The Macintosh II ROM is not "32-bit clean", and so has problems with more memory. But there is a later software update that is supposed to make a Mac II 32-bit clean (I assume by providing replacements for many of the ROM routines.) Unfortunately this doesn't work in Mini vMac yet, for unknown reasons. Maybe in the future. Meanwhile, you could try Basilisk II.

> I've received a "report" that there was a third party upgrade for the original Mac that allowed it to support more than 512K of memory. So presumably it is possible for Mini vMac to do the same. I have not investigated this yet.

So, I guess it's impossible for now...

Thanks !

**Comment by zydeco** [comment]
Indeed, this is not supported by Mini vMac yet.

You can try my BasiliskII port: https://github.com/zydeco/macemu/tree/ios
It's still a bit incomplete, but the iOS stuff is on the ios branch, you can build and run the project at BasiliskII/src/iOS

Jesús A. Álvarez

**Comment by WeedyWeedSmoker** [comment]
Thank you so much for that info...

I was not aware of this port you made, this is great news indeed !

**Comment by WeedyWeedSmoker** [comment]
@zydeco : I just tried the Basilisk II port on my jailbroken iPad v2 12,9", and it works so great !

The only thing that's a drawback from your equally great minivmac4ios is the touchscreen emulation not responding as well as on the minivmac4ios, I had to resort to trackpad emulation, and the options not easily accessible with a 2 fingers swipe...

Otherwise, I'm so glad you mentioned it, I would never have known it exists, and it really is great...

Thank you so much !
