### ISSUE TITLE
Mini vMac doesn't change emulated machines on reboot

### ISSUE THREAD

**Issue by vaporstack** [zydeco/minivmac4ios#26]
Changing the emulated machine doesn't take effect upon restart, I have to force quit the app using the iOS task manager.

I tried looking through the source to see if I could find the cause since pull requests are nicer than opening issues, but no luck (yet)

**Comment by zydeco** [comment]
It's supposed to kill itself if there's no disk inserted (see [applicationDidEnterBackground:](https://github.com/zydeco/minivmac4ios/blob/3ff092ded55ca678c27969d85e52a9f1ddd1866f/Mini%20vMac/AppDelegate.m#L118)), is this not working?

What device and iOS version is it happening on?

**Comment by vaporstack** [comment]
Ahha!  Forcing it to the background did the trick. The language led me to believe that shutting down the machine after changing emulated types and clicking the text reboot link would do it. My apologies, and many thanks for this amazing port!
