### ISSUE TITLE
i Have a old ipod 1st gen can someone give me a old build for ios 3.1.3

### ISSUE THREAD

**Issue by snes666** [zydeco/minivmac4ios#30]
im looking for a .deb file of of one of your builds from years ago as i dont know how to build it

**Comment by zydeco** [comment]
I have uploaded the last build of the 1.2.2 version here, it should work on your device:
https://github.com/zydeco/minivmac4iphone/releases/tag/v1.2.2

I remember trying it on the 1st gen iPod Touch, and it was a little slower than the iPhone 3G, sometimes it couldn't keep up.

**Comment by snes666** [comment]
yeah i got it to work on it  but itried loading prince of persia and
it got cornered to the very bottom of my screen how do i fix this
