### ISSUE TITLE
Can you add CD ROM support so i can play doom 2 and myst

### ISSUE THREAD

**Issue by snes666** [zydeco/minivmac4ios#32]

**Comment by snes666** [comment]
Yeah is there any way you can add CD ROM support for such games as DOOM II and Myst
and can you add support for Rom files such as Powerbook 190 And other 68LC040 Prossecor macs
and if were to use a Powerbook ROM file do you think the battery signal on the emulated machine could show how much battery life ive got on my iPhone also im using an iPhone 4 now on ios 7.1.2 and the 2 latest updates cause the emulator to crash on startup when I click the app to open so if you could add/fix these things it would be helpful 

Thanks very much

**Comment by zydeco** [comment]
Adding support for other machines and devices is out of scope for this project, as it’s a port of Mini vMac. You might want to try [Basilisk II](https://github.com/zydeco/macemu/tree/ios/BasiliskII/src/iOS) for this, but it requires iOS 8.

Which exact versions don’t work? How are you installing them? Is your iPhone 4 jailbroken?

**Comment by snes666** [comment]
2.3 and 2.2.4 I install them through your .deb files as yes I used pangu jailbreak since im stuck on mac osx 10.6.8 do you think I might be able to use fusionpc on idos 2 I saw this video but I don't know how to do it https://www.youtube.com/watch?v=Hl6mK9q5Pic

**Comment by zydeco** [comment]
As it turns out 2.2.3 is the last version to support iOS 7.
