### ISSUE TITLE
Mac II emulation on iPhone 4 crashes emulator with bad checksum error

### ISSUE THREAD

**Issue by snes666** [zydeco/minivmac4ios#33]

**Comment by snes666** [comment]
@zydeco

**Comment by zydeco** [comment]
Does it actually crash? If the ROM checksum is wrong (because it's not the correct ROM, or it's corrupted), it should show the error message and then stay on a black screen, since it can't boot without a ROM.

**Comment by snes666** [comment]
do you know what website i should search for in google for this ROM also i got mini vmac from cydia

**Comment by snes666** [comment]
@zydeco

**Comment by zydeco** [comment]
Downloading ROMs is considered of a grey area, so I can't help you with that.
