### ISSUE TITLE
UI is illegible with new dark mode

### ISSUE THREAD

**Issue by vaporstack** [zydeco/minivmac4ios#36]
I tried to take a stab at fixing this (I think it involves removing constant colors and stuff) but I'm inexperienced with storyboards/nibs/etc

basically in dark mode all of the disk selection/emulator options UI it's not black on black but it's pretty close. I can attach screenshots if needed. I can guess which disk image needs to be mounted based on my knowledge of what I put in the folder but it's very hard to read.

as always, thank you for your amazing work!

**Comment by vaporstack** [comment]
![IMG_4663](https://user-images.githubusercontent.com/8366060/81375859-3d4b9580-90b7-11ea-85d0-70266ab540e2.PNG)

**Comment by zydeco** [comment]
Hello, thanks for your report,
I've implemented this today in [v2.3.1](https://github.com/zydeco/minivmac4ios/releases/tag/v2.3.1), for the Insert Disk, Settings and keyboard views.
