### ISSUE TITLE
Dynamic screen resolution for portrait/landscape?

### ISSUE THREAD

**Issue by gingerbeardman** [zydeco/minivmac4ios#41]
Right now I have two variations of Macintosh Plus:

1. 512x342 (standard)
2. 512x684 (double height)

Run-in on 12.9" iPad Pro @ 2048x2732 pixels it fits almost exactly (@4x would be 2048x2760)

So I was wondering if it would be feasible to have the emulator dynamically change its resolution when the iPad is rotated. 

Currently I am switching emulators whenever I want to change orientation, which is less than ideal.

**Comment by zydeco** [comment]
Unfortunately this is not possible with Mini vMac (without a lot of hacking I think – even in Macintosh II emulation the resolution is set at compile time).

You can try my [iOS port of BasiliskII](https://github.com/zydeco/macemu/tree/ios/BasiliskII/src/iOS), which lets you switch the resolution at runtime (in the emulated Mac's control strip, or Monitors control panel), and adds landscape/portrait resolutions based on the device it's running on.

**Comment by gingerbeardman** [comment]
Thanks! I'll try that.

**Comment by gingerbeardman** [comment]
Sadly @zydeco I'm unable to build your iOS port of BasiliskII to either the Simulator or device.

I get three errors regarding `pointerInteraction`.

<img width="248" alt="Screen shot 2021-03-26 at 20 28 36" src="https://user-images.githubusercontent.com/49612/112689219-e5a24e00-8e71-11eb-82d4-1dfcb8935e00.png">

I see that's used with `#ifdef __IPHONE_13_4` in various places, but I'm at a loss how things need to be setup. I've just loaded and immediately built the project with no changes other than Signing Team ID.

Any pointers?

**Comment by zydeco** [comment]
What version of Xcode are you using?

**Comment by gingerbeardman** [comment]
I'm using Xcode 11.3.1 on Mojave 10.14.6, highest iOS I can target is 13.3 but I am leaving it as it came targeting iOS 8.0.

Anyway, I just commented out the follow lines:

if (@available(iOS 13.4, *)) {
    pointerInteraction = [[UIPointerInteraction alloc] initWithDelegate:self];
    [pointingDeviceView addInteraction:pointerInteraction];
}

And it's building 👍

**Comment by gingerbeardman** [comment]
It seems that code is to enable mouse support. I'm OK to miss that until I upgrade.

BasiliskII is working great! 

I only had to switch from 7.1 to 7.5.5 to be able to access Monitors with resolution change.

**Comment by gingerbeardman** [comment]
Just to say thanks once again.

I did a custom build adding on two more resolutions:

```
    [videoModes addObject:[NSValue valueWithCGSize:CGSizeMake(512, 342)]];
    [videoModes addObject:[NSValue valueWithCGSize:CGSizeMake(512, 683)]];
```

And made it so that nearest neighbour scaling is always on

```
    NSString *filter = kCAFilterNearest;
    videoLayer.magnificationFilter = filter;
    videoLayer.minificationFilter = filter;
```

so that I can have a more chunky half resolution display.

**Comment by gingerbeardman** [comment]
@zydeco I've noticed that when doing the above to get half-size extra-chunky graphics, there is an irregularity every resulting in some pixels being less wide than others even though the total width is correct. 

Could this be a tile rendering issue? SDL? 

Any thoughts @zydeco?

<img width="220" alt="Screen shot 2021-03-28 at 14 37 52" src="https://user-images.githubusercontent.com/49612/112755290-e7862180-8fd7-11eb-9305-b2f97825d85e.png">

**Comment by gingerbeardman** [comment]
Ah, it seems that 512x683 isn't filling the screen when it ought to be. I'll look into this.

**Comment by gingerbeardman** [comment]
I have no idea why that's not filling the screen, but I ended up at these resolutions to work around the problem.

```
[videoModes addObject:[NSValue valueWithCGSize:CGSizeMake(512, 672)]];
[videoModes addObject:[NSValue valueWithCGSize:CGSizeMake(683, 502)]];
```

**Comment by gingerbeardman** [comment]
Let me know if there's a better place for me to ask BasiliskII for iOS questions.

I'd like to create/edit a custom keyboard, is there a visual app to manage the JSON or were they generated by hand or some other way?

https://github.com/zydeco/macemu/tree/ios/BasiliskII/src/iOS/Keyboard%20Layouts

I'm currently looking at Apple Pencil mode as well as this.

Thanks!

**Comment by gingerbeardman** [comment]
@zydeco I've set up discussion thread here: https://www.emaculation.com/forum/viewtopic.php?f=6&t=11149

I'm trying to add some features (Apple Pencil mostly) but I am very rusty with Objective-C so please let me know if they are unrealistic for a born-again-noob. Thank you!

**Comment by zydeco** [comment]
Since the keyboard system is the same on both emulators, it's ok to talk about it here. I never got around to making a graphical editor, but to create the layouts I put together a small app with the keyboard classes and ran it on the simulator, and it had a reload button to see the changes quickly, I'll see if I find it.

When I was looking into the pencil support, I didn't find a satisfactory way to decide when to ignore non-pencil touch events, checking if the pencil is connected through Bluetooth seems error prone (what if it's connected but you're not using it?). But maybe an option in settings would be enough to solve this. I'll give it a look again this weekend (I have a pencil now).

**Comment by gingerbeardman** [comment]
Thanks!

I've been looking at [SpeedSketch](https://developer.apple.com/documentation/uikit/touches_presses_and_gestures/leveraging_touch_input_for_drawing_apps) (Apple example code, Swift) and that uses two StrokeGestureRecognizers: one for Finger and one for Pencil. It tracks the time of the last Pencil interaction and times out after a while. If Pencil is being used to draw then one finger can be used to pan the view, if finger is being used to draw then two fingers can pan. It's quite elegant.

Here's my custom keyboard for my drawing app: 

![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2021-04-01 at 22 00 16](https://user-images.githubusercontent.com/49612/113362553-8b5c2e00-9346-11eb-9bd1-70a7e1a83daf.png)

**Comment by gingerbeardman** [comment]
It would be very useful to have custom resolutions that exclude the area needed for the keyboard, so it can be left up at all times and not overlap the screen area.

Let me know if you want me to have a go at that? Currently I hard code them for my device, so would need to write proper code for this.

**Comment by gingerbeardman** [comment]
> But maybe an option in settings would be enough to solve this. I'll give it a look again this weekend (I have a pencil now).

Did you have a chance to take a look:?

**Comment by gingerbeardman** [comment]
Hi @zydeco I upgraded to Big Sur 11.3.1 these past few days. The macemu code as it is won't build on Xcode 12, some errors regarding qemu(?) and more. But good news is that you can still use Xcode 11.7 to build it. 

I'll take a look at the changes required. Cheers!

**Comment by zydeco** [comment]
> > When I was looking into the pencil support, I didn't find a satisfactory way to decide when to ignore non-pencil touch events, checking if the pencil is connected through Bluetooth seems error prone (what if it's connected but you're not using it?). But maybe an option in settings would be enough to solve this. I'll give it a look again this weekend (I have a pencil now).
> 
> @zydeco did you have a chance to take a look?

Sorry, I haven't had time to look into this yet.

> Hi @zydeco I upgraded to Big Sur 11.3.1 these past few days. The macemu code as it is won't build on Xcode 12, some errors regarding qemu(?) and more. But good news is that you can still use Xcode 11.7 to build it.
> 
> I'll take a look at the changes required. Cheers!

It seems this is caused by the C++ header search order and case-insensitive file system, it now picks slirp's `VERSION` file for `#include <version>`, a workaround is to [rename the file](https://github.com/zydeco/macemu/commit/55cfd67825d07f5364b75f0cf88108b2d42b4b8e) 🤷

I haven't implemented "portrait with space for keyboard" resolution yet, since it depends on the chosen keyboard layout, and the keyboard is not created yet, but I've [fixed the custom resolution option](https://github.com/zydeco/macemu/commit/1f7803c3e3411039707a5a5896236118c1edb6bc) which wasn't having any effect.

**Comment by gingerbeardman** [comment]
Yes, I managed to get it building on Xcode 12 by deleting the `VERSION` file. Maybe a bit too severe a solution? Then two more errors regarding `spinlock` I simply commented out.

Did you think about putting this on AltStore like you did wit minivmac? I have a private ad-hoc build I share with a couple of friends but it's not ideal.
