### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by person246** [zydeco/minivmac4ios#42]
When I try to install the ipa file, it gives me an error saying “Could not install Mini vMac because it’s integrity could not be verified”. How to fix this, or is it an issue with everybody?

**Comment by zydeco** [comment]
How are you installing it?
The ipa file is installable with AltStore, or some other tool to resign it.

Jesús A. Álvarez

**Comment by person246** [comment]
Using installonair. AltStore was giving me errors about altserver, so I didn’t use that.

**Comment by person246** [comment]
iOS 14

**Comment by person246** [comment]
And my iPhone 4s at iOS 9 is showing this error
![image](https://user-images.githubusercontent.com/85662112/121767868-112cfe80-cb6c-11eb-9e0b-18b5c77b2455.jpg)

**Comment by zydeco** [comment]
I think it won’t work with installonair because the ipa is not signed for distribution, you need to resign it to install on your device. The easiest is to use AltStore.

Jesús A. Álvarez
