### ISSUE TITLE
Sound doesn't work on iOS 16 when sideloading with AltStore

### ISSUE THREAD

**Issue by BlastBlaster17** [zydeco/minivmac4ios#46]
Hi,

For some reason, the sound doesn't appear to be working on iOS 16 on my iPhone 11 when I'm using AltStore to sideload the provided iOS release IPA. Now, granted, this might just be because I used the release instead of the source code, but the reason I did that is that compiling from source code always gives me many errors. So this needs to be fixed. Can you please do it?

**Comment by zydeco** [comment]
Is your phone muted?
I just tried sideloading the release on an iPhone 13 mini with iOS 16.3.1, and AltStore 1.6, and it plays sounds correctly when the phone is not muted.

**Comment by BlastBlaster17** [comment]
No, my phone wasn't muted.

**Comment by BlastBlaster17** [comment]
In fact, I think that might be the problem. You're using an iPhone 13 mini, and I'm using an iPhone 11. Another problem might be the fact that my iOS wasn't updated.

**Comment by zydeco** [comment]
- What iOS version does this happen in?
- Which mac are you emulating?

The startup chime should play in all variants (Plus, 128K and II) when the volume is up and the phone is not on mute, if the speed is not 1x it only plays correctly on the Plus (but other sounds should still work). If you're emulating a Mac II, you might need to select an output device in the Mac's Sound control panel.

**Comment by BlastBlaster17** [comment]
Oh, that was the problem. I had silent mode on.
