### ISSUE TITLE
Document build process

### ISSUE THREAD

**Issue by ryandesign** [zydeco/minivmac4ios#47]
Could you update the readme to document the build process?

For example, explain that you need to download from git (not from a tarball) and also fetch the submodules. This has come up before in #14 and #16 but there, the users experienced build failures which made it clear that files were missing. Today, I am building with Xcode 13.2.1 and, unexpectedly, the build succeeds despite the missing files and then Xcode shows the error:

> Executable Not Found
> 
> /Users/…/Library/Developer/Xcode/DerivedData/Mini_vMac-ddsiulpblselfncmyzrihvlcjnuc/Build/Products/Debug-iphoneos/Mini vMac.app is not a valid path to an executable file. Please rebuild the project to ensure that all required executables are created. Check your project settings to ensure that a valid executable will be built.

After fetching the submodules and building again, it gets further.

It was also necessary to go to the Signing & Capabilities tab and change the team from yours to my personal team and change the bundle identifier to something unique to me.

Finally, after getting the app onto my iPad, Xcode wouldn't launch it, with the cryptic error "Security". Tapping the icon on the iPad home screen provided more context, saying the developer was untrusted and that I could fix it in Settings. Specifically, what I had to do was go to Settings, General, Device Management, my developer profile, and indicate that this developer was trusted.

I knew these things at one point but it's been years since I did any iOS development and I had forgotten. Having this stuff spelled out clearly in the readme would help newbies and the forgetful.

I know Apple likes to move stuff around, so the process may be different in other Xcode or iOS versions. I'm using iOS 9.3.5.

**Comment by zydeco** [comment]
Thanks for the suggestion, I've added some instructions to the readme now, with a link to the Apple documentation that explains some parts with more details:

> ### Building from source
> 
> To build the project, make sure you check out the repository and submodules:
> 
> ```
> git clone https://github.com/zydeco/minivmac4ios.git
> cd minivmac4ios
> git submodule update --init --recursive
> ```
> 
> The folders `minivmac`, `libmfs` and `libres` should not be empty. The source code zip file you can download from GitHub does not include all dependencies.
> 
> To install run the app on your device with Xcode, you'll to perform some [additoinal steps](https://developer.apple.com/documentation/xcode/enabling-developer-mode-on-a-device):
> 
> * Pair the device with Xcode
> * Specify your Apple ID in the Account preferences in Xcode.
> * Change the Team (to your own) and Bundle Identifier (for example, change the `net.namedfork` prefix to your own) in the “Mini vMac” target, under the “Signing & Capabilities” tab.
> * Enable [Developer Mode](https://developer.apple.com/documentation/xcode/enabling-developer-mode-on-a-device) on your device (iOS 16 and later).
> * On older iOS versions, trust your developer profile in the iOS Settings (under General > Device Management) after installing the app for the first time.

I think trusting specific developer profiles is gone since iOS 16, but I don't have any device with an older iOS to try.
