### ISSUE TITLE
Add Mac II 512x384 option

### ISSUE THREAD

**Issue by ryandesign** [zydeco/minivmac4ios#48]
It would be great to have a Mac II 512x384 option (in addition to the existing 1024x768 and 640x480 options).

I attempted to add it myself but I don't use Xcode often and it's being incomprehensible to me again.

It would be great if it were easier to add new configurations. Maybe documenting the process of adding a new configuration would be helpful.

**Comment by zydeco** [comment]
Hi, I've added it in #e8c8b8375f1062dca2e8dfda05e7ba3886474616 
The way to add new machines is documented [on the wiki](https://github.com/zydeco/minivmac4ios/wiki/Adding-a-new-emulated-machine), although it's not very discoverable. I'll add a link from the readme.
