### ISSUE TITLE
Add inter-app audio support

### ISSUE THREAD

**Issue by adespoton** [zydeco/minivmac4ios#5]
Should be possible to enable the audio output to be captured by inter-app audio.  Not sure if it would be possible to hook up a virtual microphone via inter-app audio, as I don't think Paul has exposed a virtual microphone in the emulator core -- and the original hardware used serial or SCSI for the  Plus, and later ADB for microphone input.

**Comment by zydeco** [comment]
I'm not convinced this would be of any use, it would only allow recording audio from another app running on the iOS device, I find it more convenient to record both audio and video from a mac connected by USB, or via airplay.

Audio input is not currently possible, none of the macs that Mini vMac emulates supported it (the first to add it were the LC and IIsi).

**Comment by adespoton** [comment]
Ah; I didn't realize there was Airplay support!  That's definitely a simpler solution.  We can probably close this one as alternate solution available :)
