### ISSUE TITLE
Upload to the App Store? 

### ISSUE THREAD

**Issue by fruitbow1** [zydeco/minivmac4ios#52]
Hey! 

Love the app and haven’t found any issues as of yet, are you considering uploading this app to the App Store since the rules have changed? 

Thanks,
Callum

**Comment by gingerbeardman** [comment]
I was also thinking about this, but not ever emulator is equal. Apple still don't allow some of the technologies that certain emulators use (eg. JIT compilation) and also the fact that this runs modifyable code could also be a problem (ROMs are fixed, disk images can be modified)

> 4.7 Mini apps, mini games, streaming games, chatbots, plug-ins, and game emulators
> Apps may offer certain software that is not embedded in the binary, specifically HTML5 mini apps and mini games, streaming games, chatbots, and plug-ins. Additionally, retro game console emulator apps can offer to download games. You are responsible for all such software offered in your app, including ensuring that such software complies with these Guidelines and all applicable laws. Software that does not comply with one or more guidelines will lead to the rejection of your app. You must also ensure that the software adheres to the additional rules that follow in 4.7.1 through 4.7.5. These additional rules are important to preserve the experience that App Store customers expect, and to help ensure user safety.
> 4.7.1 Software offered in apps under this rule must:
> follow all privacy guidelines, including but not limited to the rules set forth in Guideline 5.1 concerning collection, use, and sharing of data, and sensitive data (such as health and personal data from kids);
> include a method for filtering objectionable material, a mechanism to report content and timely responses to concerns, and the ability to block abusive users; and
> use in-app purchase in order to offer digital goods or services to end users.
> 4.7.2 Your app may not extend or expose native platform APIs to the software without prior permission from Apple.
> 4.7.3 Your app may not share data or privacy permissions to any individual software offered in your app without explicit user consent in each instance.
> 4.7.4 You must provide an index of software and metadata available in your app. It must include universal links that lead to all of the software offered in your app.
> 4.7.5 Your app must share the age rating of the highest age-rated content available in your app.

**Comment by zydeco** [comment]
It doesn't seem that the rules have changed in any way that would allow Mini vMac, but specifically retro game consoles.

An article on Macrumors seems to clarify a bit more:

> Notably, Apple confirmed to us that emulators on the App Store are permitted to load ROMs downloaded from the web, so long as the app is emulating retro console games only. [1]

[1]: https://www.macrumors.com/2024/04/15/apple-further-explains-igba-removal/

**Comment by upintheairsheep** [comment]
> It doesn't seem that the rules have changed in any way that would allow Mini vMac, but specifically retro game consoles.
> 
> An article on Macrumors seems to clarify a bit more:
> 
> > Notably, Apple confirmed to us that emulators on the App Store are permitted to load ROMs downloaded from the web, so long as the app is emulating retro console games only. [1](https://www.macrumors.com/2024/04/15/apple-further-explains-igba-removal/)

I think this guideline is saying “don’t put Nintendo Switch emulators” but the old Mac will likely get allowed.

**Comment by austintatiousness** [comment]
Apple allowed UTM SE on visionOS. I have no idea how it got through. I got Ubuntu running on it (SLOW because JIT is disabled). I haven’t got any of the Mac OS classic versions to boot. Again this isn’t sideloaded. I’ve checked every day to see if it gets deleted. Maybe it is worth a try to get minivmac on there?

**Comment by zydeco** [comment]
I wanted to at least try and get it notarised to distribute on AltStore PAL in the EU, but given the rejection of UTM SE (on the basis of “PC is not a console”), it would seem like a waste of time. It's highly unlikely the App Store Review Board will think the Macintosh is a console.

> After almost two month long review process, Apple has rejected UTM SE from the iOS App Store as well as from notarization for third party app stores. Their reasoning is that rule 4.7 which Apple recently introduced that allows for Delta, PPSSPP, and other emulators to be allowed does NOT apply to UTM SE. The App Store Review Board determined that "PC is not a console" regardless of the fact that there are retro Windows/ DOS games for the PC that UTM SE can be useful in running. Additionally, Apple's stance is that UTM SE is not allowed on third party marketplaces either because rule 4.7 also applies to Notarization Review Guidelines.
>
> We will adhere by Apple's content and policy decision because we believe UTM SE (which does not have JIT) is a subpar experience and isn't worth fighting for (see https://oatmealdome.me/blog/why-dolphin-isnt-coming-to-the-app-store/). We do not wish to invest any additional time or effort trying to get UTM SE in the App Store or third party stores unless Apple changes their stance.
> 
> Source: https://x.com/UTMapp/status/1799647652

**Comment by gingerbeardman** [comment]
Source link is truncated, should be https://x.com/UTMapp/status/1799647652134654045

**Comment by gingerbeardman** [comment]
If you have the energy now that UTM SE is on iOS might you try for AltStore?

**Comment by zydeco** [comment]
I’ll try and see what the notarisation process is like.
From what I’ve read it might be long.

**Comment by zydeco** [comment]
Mini vMac has been rejected for notarization by App Review, after an initial rejection and my appeal. Emulators are only allowed as long as they don't emulate Apple systems.

> The App Review Board has determined that the decision to reject your app, Mini vMac, was based entirely on App Review Guidelines, Developer Program License Agreement, and Alternative EU Terms Addendum violations present in the app and that the rejection feedback is valid. We would like to take this opportunity to explain why your app was rejected. Use of Apple’s software is limited to the terms of the license for such software. Apple does not license its Mac operating system software for use outside of an Apple-branded computer. Your app necessarily involves and promotes the use of Mac operating system software on devices other than Apple–branded computers and such use goes beyond of the scope of its license terms. Notarization of your app thus would contravene the terms of Apple's software licenses. Additionally, your prominent use of Apple’s MAC mark in the app name; MACINTOSH in the subtitle, and a Macintosh graphic in the icon for an operating system software product improperly and confusingly suggests or implies that the app has an affiliation, endorsement, or sponsorship by Apple and is in contravention of Apple’s Trademark Guidelines. For additional information, please refer to the previous messages you received in App Store Connect. You may also review the App Review Guidelines to learn more about this issue. If you think the App Review Guidelines can be clarified or improved, you may consider suggesting guideline changes. Best regards, App Review
