### ISSUE TITLE
Emulated trig functions are wrong?

### ISSUE THREAD

**Issue by crutch-meef** [zydeco/minivmac4ios#53]
Hi, still love this and use it every single day.
I think the emulated cosine function is somehow wrong.  See screenshot, I wrote a trivial program to compute cos(π) in Symantec C++ 7 (using the C compiler) and consistently get +1 instead of -1.  Cos(1) gives 0.84 which is also wrong (should be about 0.54).  I tried running a random 3rd party fancified calculator DA (Calculator+, also in screenshot) and get the same wrong values.

Sines appear wrong also.

Any help appreciated.

![IMG_0406](https://github.com/zydeco/minivmac4ios/assets/76711464/9e3766f1-e219-4f85-a3b3-7e03a28dca73)

**Comment by gingerbeardman** [comment]
C is converted into machine code, or sometimes interpreted, so there's a bunch of stuff happening before the CPU even executes instructions (which aren't sin and cos directly, but rather complex lookups and operations to figure out equivalents). If the CPU emulation was wrong the emulated machine wouldn't even boot.

So, I don't think this has anything to do with the emulator, but rather your use or understanding of C. 

There are lots of different flavours of C, and many different specs. Without knowing which you're using it's hard to give precise help. I feel the answer will be in the documentation for the C you're using.

Does your C trig functions expect degrees or radians? What numeric data type does it expect: single, double, long, signed, unsigned? And so on.

**Comment by gingerbeardman** [comment]
Here we go:

```c
#include <stdio.h>
#include <math.h>

int main()
{
    double x;
    double result;

    x = 3.14159;
    result = cos(x);
    printf("cos(%.2lf) = %.2lf\n", x, result);

    x = 1.0;
    result = cos(x);
    printf("cos(%.2lf) = %.2lf\n", x, result);

    return 0;
}
```

<img width="752" alt="Screen shot 2024-04-27 at 23 43 29" src="https://github.com/zydeco/minivmac4ios/assets/49612/dae97716-4284-428c-bf03-6be334cb00b6">

**Comment by crutch-meef** [comment]
Thanks @gingerbeardman I should mention I’m a fairly expert level 68k C and assembly programmer so I’m very familiar with the issues you mention.  I’m not sure if you noticed, but I mentioned in my original post that I also ran a vintage desk accessory from 1990 and got the same incorrect result when I took the cosine of 1 radian or pi radians. I can’t see how that could possibly be happening without something weird going on under the hood. I’m using the C standard library, same as you, in my case running Symantec C++7 under 7.5.5.

I will try your exact code shortly, though I can’t see how it would give a different result….

**Comment by gingerbeardman** [comment]
Just a disclaimer their had to run my code in BasiliskII because it's all I had to hand. 

I'm intrigued about this one!

**Comment by crutch-meef** [comment]
@gingerbeardman I ran your exact code and got the same bad result.

I stepped thru Macsbug and the cos function is calling into the SANE package, which is in turn executing some 68881 instructions such as FMOVE (I am emulating a Mac II with a 68881).  I suspect that there is something funky with the way the FPU instructions were implemented that is causing something weird to happen.

This issue _goes away_ if I compile my code with Symantec’s “Use 68881 instructions” option checked, in which case my disassembly shows that an FCOS instruction is being generated, which works fine.  (Presumably the legacy DA I am checking against, Calculator II, is instead using SANE and is running into the same weird emulator issue that I’m seeing.). Needless to say, using 68881 instructions should not be necessary and SANE should work.

![IMG_0407](https://github.com/zydeco/minivmac4ios/assets/76711464/5eea5840-bed1-4a14-a2d7-5d26c980ae8f)

**Comment by gingerbeardman** [comment]
Absolutely agree. Thanks for looking into it further.

**Comment by zydeco** [comment]
Thanks for the report, I wrote a similar app and found the issue only happens in the Mac II emulation, but not when emulating a Mac Plus. So it seems like a subtle bug in the 68020 emulation 🤔 

It also happens in the x86_64 and x86 builds from the [official page](https://www.gryphel.com/c/minivmac/b_dl_mii.html), which rules out some 64-bit or arm-specific issue:
![mnvm26_macII_sane_bug](https://github.com/zydeco/minivmac4ios/assets/158216/7b722675-3872-4099-9192-6ca3feb5601c)

**Comment by crutch-meef** [comment]
Oh interesting and I just noticed this disclaimer on the official page which I had never paid attention to before … seems this is exactly what I stumbled on. 

“Warning : Macintosh II emulation in Mini vMac is incomplete, and should not be relied on to give accurate results, particularly numeric results. (Emulation of the Floating Point Unit is the main incomplete part.) It does seem suitable for games, many of which appear to work perfectly well.“

**Comment by zydeco** [comment]
I'm closing this since it's a known bug in Mini vMac
