### ISSUE TITLE
Update Releases page with a new IPA?

### ISSUE THREAD

**Issue by crutch-meef** [zydeco/minivmac4ios#54]
Apologies if this is the wrong place to put this - it would be handy to update the Releases page https://github.com/zydeco/minivmac4ios/releases with a new IPA.  The posted one doesn't include the recent fix to prevent (for example) Cmd-W from shutting down the app, and posting the IPA makes it much handier to sideload with AltStore (which is really great!).

As it is I built myself and pointed AltStore at my own IPA, which is fine just a bit more cumbersome, especially for newer users I expect.  Thanks!

**Comment by zydeco** [comment]
Thanks for reminding me!
I've released the current version as [2.6](https://github.com/zydeco/minivmac4ios/releases/tag/v2.6)
