### ISSUE TITLE
iOS 18 support?

### ISSUE THREAD

**Issue by Samuel525432** [zydeco/minivmac4ios#55]
So I was wondering can mini Vmac support iOS 18?
What I mean is can mini vmac supports iOS 18
iOS 18b2
iPhone 14 Pro Max btw

**Comment by zydeco** [comment]
I haven't installed iOS 18 or the developer tools betas yet, I'll try once it's released.
I don't recall it breaking with previous iOS releases, so it probably works.

**Comment by Samuel525432** [comment]
Well the last time I installed the latest version I think it was 2.6 and it crashed

**Comment by Samuel525432** [comment]
Maybe of that JIT stuff idk

**Comment by zydeco** [comment]
I'll close this issue, I've been using Mini vMac on iOS 18 for a while without issues, no code changes were required.
