### ISSUE TITLE
Can Mini VMac support Mac OS 8.0?

### ISSUE THREAD

**Issue by Samuel525432** [zydeco/minivmac4ios#56]
I was wondering can Mac OS 8 work in Mini vMac?

**Comment by zydeco** [comment]
No, Mini vMac emulates a Macintosh Plus, Macintosh II or Macintosh 128K.

The Macintosh Plus and II can run up to 7.5.5, and the 128K up to System 3.2/Finder 5.3.

To run Mac OS 8 you can use [BasiliskII](https://github.com/zydeco/macemu/tree/ios/BasiliskII/src/iOS)

**Comment by Samuel525432** [comment]
But here’s the thing when I make my hard disk it crashes the mini vmac idk why 
Trying to use system 7.5.5

**Comment by zydeco** [comment]
Closing this since the original question is answered. If you have issues with a pre-made 7.5.5 image, try reinstalling it from an installer disk, so you can choose the right version for the machine you're emulating.
