### ISSUE TITLE
Is been a long time that Basilisk was been released maybe you can update it or something?

### ISSUE THREAD

**Issue by Samuel525432** [zydeco/minivmac4ios#57]
So I was wondering can you update Baslilskl
Like add new feature or something 
Like allowing Mac OS 8 games and stuff

**Comment by gingerbeardman** [comment]
- it works
- it already supports Mac OS 8

**Comment by Samuel525432** [comment]
Maybe make Mac OS 9 support?

**Comment by gingerbeardman** [comment]
That requires an emulator that supports the PPC CPU architecture. Use SheepShaver.

BasiliskII supports only the M68K CPU architecture.
