### ISSUE TITLE
Testfight support?

### ISSUE THREAD

**Issue by Samuel525432** [zydeco/minivmac4ios#59]
Is there some way you can put Minivmac4ios on Testfight?
What I mean is are you planning to put Minivmac4ios on Testfight iOS?

**Comment by zydeco** [comment]
I hadn't considered this before, since it doesn't comply with the App Store rules (it probably wouldn't pass the TestFlight mini-review), but now that TestFlight can be used also when distributing via third party app stores, I can try, after seeing how the notarisation process goes.

**Comment by Samuel525432** [comment]
Ok thx for letting me know 👍

**Comment by Samuel525432** [comment]
Is there any update about the TestFlight support?

**Comment by zydeco** [comment]
No, I'd like to look into notarising this weekend if I have some time

**Comment by Samuel525432** [comment]
What does that mean exactly

**Comment by Samuel525432** [comment]
Any Updates?

**Comment by zydeco** [comment]
Since Apple has rejected Mini vMac for notarization, I will not be using TestFlight to distribute any betas.

**Comment by Samuel525432** [comment]
bruh
