### ISSUE TITLE
Add Import/Export support

### ISSUE THREAD

**Issue by adespoton** [zydeco/minivmac4ios#6]
... via 
[ExportFl](http://www.gryphel.com/c/minivmac/extras/exportfl/index.html) - exports files from Mini vMac 
[ImportFl](http://www.gryphel.com/c/minivmac/extras/importfl/index.html) - imports files into Mini vMac

Since apps are sandboxed, this would have to grab files from/put files in the Documents folder.  Possibly some tie-in to inter-app sharing?

**Comment by zydeco** [comment]
Implemented in e220494dc515fac8e483b5e2a7813020cda8a0ee and f180642b3352bf1c44de40507b153d4120420842

When the Insert Disk menu shows, if the frontmost app name is `ImportFl`, it will let you choose any file in the Documents directory to insert as a disk.
