### ISSUE TITLE
No Bluetooth Keyboard support on v2.1.1 on iOS 8

### ISSUE THREAD

**Issue by jakbrown73** [zydeco/minivmac4ios#8]
Hi Dude

I was checking for all the new features you added to your ios port on my I pad Air 2,  
eg.. More Speed options, No more crashes when you create disk images and many other good things.
But the only thing missing was the Bluetooth keyboard support, that was working fine on the release 2.1 

I am Emulating Mac II Finder 7.5.5 wit 256 colors, no sound, very good speed, I believe this is one of the best ports for Ipad and Iphone. lots of games runs perfectly in full color.

You are doing a very good job 

Thank you so much for this port

**Comment by zydeco** [comment]
What iOS version are you running? Is it jailbroken? I tested it in iOS 9, and disabled physical keyboard events for iOS 8 and below, because it was crashing when using the on screen keyboard in text fields (creating and renaming disk images)



Jesús A. Álvarez

**Comment by jakbrown73** [comment]
IOS 8.1.2 and it is jailbroken
Ohh i see, so under ios 9 the physical keyboard works fine?

**Comment by zydeco** [comment]
Yes, I've tested it in iOS 9 (not jailbroken, but it shouldn't matter)
